spring.application.name=JWTToken

server.port=8080

# DB (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/jwtDB
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT configuration
jwt.secret=8fK9pL2mQ7xR4vT8wY1zA5cB3nD6eF0gH2jK9mPqRtUvWxYzAbCdEfGhJkLmNoP
jwt.expiration-ms=86400000

# OAuth2 Google Configuration

spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
